### ISSUE TITLE
Float32

### ISSUE THREAD

**Issue by gdkrmr** [dillondaudert/UMAP.jl#10]
I just got the following error when using an `Array{Float32}`:
```
MethodError: no method matching combine_fuzzy_sets(::SparseArrays.SparseMatrixCSC{Float32,Int64}, ::Float64)
Closest candidates are:
  combine_fuzzy_sets(::AbstractArray{T<:AbstractFloat,2}, !Matched::T<:AbstractFloat) where T<:AbstractFloat at /home/me/.julia/packages/UMAP/7orf6/src/utils.jl:61
```

**Comment by dillondaudert** [comment]
I have an idea of what's going on here. Could you provide more information on how you're calling `umap`? What if any other parameters are you passing?

**Comment by dillondaudert** [comment]
Give it a shot on the `argtypes` branch

**Comment by gdkrmr** [comment]
This is a reproducible one-liner:
```julia
julia> umap(randn(Float32, 20, 1000), 2)
ERROR: MethodError: no method matching combine_fuzzy_sets(::SparseArrays.SparseMatrixCSC{Float32,Int64}, ::Float64)
Closest candidates are:
  combine_fuzzy_sets(::AbstractArray{T<:AbstractFloat,2}, ::T<:AbstractFloat) where T<:AbstractFloat at /home/me/julia/packages/UMAP/7orf6/src/utils.jl:61
```
on the `argtypes` branch it works, but I get a weird error message:
```julia
julia> umap(randn(Float32, 20, 1000), 2)
Error encountered in spectral_layout; defaulting to random layout
2×1000 Array{Float32,2}:
 -1.32639   -0.746478  -0.933311  -1.16249   1.74564   …   1.5002   2.29761  3.04286   1.61978  -1.84504   3.19287 
  0.595433   1.85769    2.61646    0.310585  0.616751     -1.14881  2.33555  0.248531  2.17292  -0.320106  0.624897
```

**Comment by dillondaudert** [comment]
Yeah, that's due to Arpack and the `eigs` method not working on `Float32`.  I still need to look if there's a way around that.

**Comment by dillondaudert** [comment]
The spectral layout isn't necessary for umap to work, it's just a reasonable a priori initialization for the projection (which then gets optimized). The results with the randomly initialized embedding should be fine though.

**Comment by gdkrmr** [comment]
thanks, very cool package!
