### ISSUE TITLE
DescentGraph not defined

### ISSUE THREAD

**Issue by mkarikom** [dillondaudert/UMAP.jl#30]
weird issue when adding:

julia> using UMAP
[ Info: Precompiling UMAP [c4f8c510-2410-5be4-91d7-4fbaeb39457e]
ERROR: LoadError: UndefVarError: DescentGraph not defined
Stacktrace:
 [1] include(::Module, ::String) at ./Base.jl:377
 [2] top-level scope at none:2
 [3] eval at ./boot.jl:331 [inlined]
 [4] eval(::Expr) at ./client.jl:449
 [5] top-level scope at ./none:3
in expression starting at /home/myhome/.julia/packages/UMAP/Eq5Hc/src/UMAP.jl:4

**Comment by mkarikom** [comment]
Looks like NearestNeighborDescent.DescentGraph is no longer exported?

**Comment by dillondaudert** [comment]
Make sure you're using the latest version of UMAP. DescentGraph was removed in version 0.3 of NearestNeighborDescent.jl, which is what the latest version of UMAP uses.

**Comment by dillondaudert** [comment]
Were you able to fix your issue?

**Comment by mkarikom** [comment]
Hi, yes the upgrade worked.  Thanks for your help!
