### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by babaq** [dillondaudert/UMAP.jl#46]
currently, lots of dependencies are outdated, and conflicts with new versions of these packages. specifically, `Distribution`, `JLD2`, `LsqFit` and `Reexport`.

**Comment by babaq** [comment]
it seems caused by the `NearestNeighborDescent`

**Comment by dillondaudert** [comment]
NearestNeighborDescent has had a new release, as well as this package. It should fix the issue.
