### ISSUE TITLE
Is UMAP sensitive to floating point microarchitecture?

### ISSUE THREAD

**Issue by mcfefa** [dillondaudert/UMAP.jl#7]
I'm trying to run UMAP.jl on two different machines (one is a MacBook Pro and then other is a computational cluster at my institute, both using Julia 1.0) and when I run the same dataset on each of them, I get drastically different results. My MacBook shows clear groupings by communities previously detected in the data (community id was excluded when embeddings were calculated), but when I run the same data on the computational cluster, the UMAP returns a similar overall shape, but there is not longer any clear groupings based on community id (like with my MacBook). I was wondering if UMAP.jl could be sensitive to floating point microarchitecture changes between my MacBook and the computational cluster? And if there is anything I could do to fix this? I have large-ish datasets (20-100k x 12) and they take hours to run on my machine and the cluster, so I want to make sure I have consistency between the computational resources. I've have two smaller datasets (1.5k x 12, which take < 1 min to run) and I've reproduced this discrepancy multiple times across these smaller examples.

**Comment by dillondaudert** [comment]
Did you figure out the issue?

**Comment by mcfefa** [comment]
Yes, it looks like I sorted one of the datasets and not the other, which is
why things weren't matching up.
