### ISSUE TITLE
UMAP from distance matrix?

### ISSUE THREAD

**Issue by robertfeldt** [dillondaudert/UMAP.jl#8]
Having read the UMAP paper it seems to me that one should be able to use UMAP even for data which is not represented as a vector of float's, e.g. when one only has a full distance matrix. Any plans to support this in UMAP.jl?

**Comment by dillondaudert** [comment]
This is possible, and already supported in the Python umap; implementing it in UMAP.jl should be relatively straightforward. I'll try to get to it in the next week or so.

**Comment by robertfeldt** [comment]
Thanks, appreciated.

**Comment by dillondaudert** [comment]
I still need to add documentation, but you can test this out on the `dist_matrix` branch. The API is the same, just pass in your distance matrix as `X` and the metric keyword arg as `Precomputed()`.

**Comment by dillondaudert** [comment]
Just changed this a bit; instead of passing a type, pass the symbol `:precomputed`

**Comment by dillondaudert** [comment]
Released v0.1.3 with this functionality implemented
